version: '3'

services:

  php:
    container_name: ${NAMESPACE:-slamp}-php
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./:/srv/www
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    container_name: ${NAMESPACE:-slamp}-nginx
    image: nginx:latest
    ports:
      - ${HTTP_PORT:-0}:80
    volumes:
      - ./:/srv/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    container_name: ${NAMESPACE:-slamp}-mysql
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT:-0}:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}