version: '3'

services:
  php:
    container_name: ${NAMESPACE:-arvancloud}-php
    build:
      context: ./docker/php
      args:
        uid: ${UID:-1000}
    volumes:
      - ./:/srv/www
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  nginx:
    container_name: ${NAMESPACE:-arvancloud}-nginx
    image: nginx:latest
    ports:
      - ${HTTP_PORT:-0}:80
    volumes:
      - ./:/srv/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    container_name: ${NAMESPACE:-arvancloud}-mysql
    image: mysql:8.0
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - ${MYSQL_PORT:-0}:3306
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}